# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
