# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-08 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0004_order_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantily',
            new_name='quantity',
        ),
    ]
